### ISSUE TITLE
Missing dependencies for make(1)ing

### ISSUE THREAD

**Issue by fchurca** [robert-strandh/CL-reference#6]
The README could include a recommendation to make sure fig2dev is installed, probably via transfig.

**Comment by robert-strandh** [comment]
Done, thanks!

On Thu, Feb 18, 2016 at 7:07 PM, Federico Churca-Torrusio <
notifications@github.com> wrote:

> The README could include a recommendation to make sure fig2dev is
> installed, probably via transfig.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robert-strandh/CL-reference/issues/6>.
>



-- 
Robert Strandh
